# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Client.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x43lient.proto\"\x07\n\x05\x45mpty\"\x18\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\"D\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x15\n\x06sender\x18\x02 \x01(\x0b\x32\x05.User\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\x14\n\x06\x43hatId\x12\n\n\x02id\x18\x01 \x01(\t\"8\n\nMenuOption\x12\x15\n\roption_number\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2\xc6\x01\n\x0b\x43hatService\x12\"\n\x0b\x43onnectChat\x12\x07.ChatId\x1a\x08.Message0\x01\x12+\n\x14SubscribeToGroupChat\x12\x07.ChatId\x1a\x08.Message0\x01\x12\"\n\rDiscoverChats\x12\x06.Empty\x1a\x07.ChatId0\x01\x12\x1b\n\nSendInsult\x12\x05.User\x1a\x06.Empty\x12%\n\x10StartPrivateChat\x12\x05.User\x1a\x08.Message0\x01\x32\x9f\x02\n\x0f\x43lientUIService\x12\x1c\n\x0bGetUsername\x12\x06.Empty\x1a\x05.User\x12(\n\x0fShowMenuOptions\x12\x06.Empty\x1a\x0b.MenuOption0\x01\x12\"\n\x0b\x43onnectChat\x12\x07.ChatId\x1a\x08.Message0\x01\x12+\n\x14SubscribeToGroupChat\x12\x07.ChatId\x1a\x08.Message0\x01\x12\"\n\rDiscoverChats\x12\x06.Empty\x1a\x07.ChatId0\x01\x12(\n\x13\x41\x63\x63\x65ssInsultChannel\x12\x05.User\x1a\x08.Message0\x01\x12%\n\x10StartPrivateChat\x12\x05.User\x1a\x08.Message0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Client_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=16
  _globals['_EMPTY']._serialized_end=23
  _globals['_USER']._serialized_start=25
  _globals['_USER']._serialized_end=49
  _globals['_MESSAGE']._serialized_start=51
  _globals['_MESSAGE']._serialized_end=119
  _globals['_CHATID']._serialized_start=121
  _globals['_CHATID']._serialized_end=141
  _globals['_MENUOPTION']._serialized_start=143
  _globals['_MENUOPTION']._serialized_end=199
  _globals['_CHATSERVICE']._serialized_start=202
  _globals['_CHATSERVICE']._serialized_end=400
  _globals['_CLIENTUISERVICE']._serialized_start=403
  _globals['_CLIENTUISERVICE']._serialized_end=690
# @@protoc_insertion_point(module_scope)
