# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NameServer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10NameServer.proto\"\x07\n\x05\x45mpty\"\x14\n\x06\x43hatId\x12\n\n\x02id\x18\x01 \x01(\t\"1\n\x12\x43hatNamespaceEntry\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"A\n\x0bUserAddress\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"\x1e\n\x0b\x43hatAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t2^\n\nNameServer\x12\'\n\x0fRegisterAddress\x12\x0c.UserAddress\x1a\x06.Empty\x12\'\n\x0eGetChatAddress\x12\x07.ChatId\x1a\x0c.ChatAddressb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NameServer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_CHATID']._serialized_start=29
  _globals['_CHATID']._serialized_end=49
  _globals['_CHATNAMESPACEENTRY']._serialized_start=51
  _globals['_CHATNAMESPACEENTRY']._serialized_end=100
  _globals['_USERADDRESS']._serialized_start=102
  _globals['_USERADDRESS']._serialized_end=167
  _globals['_CHATADDRESS']._serialized_start=169
  _globals['_CHATADDRESS']._serialized_end=199
  _globals['_NAMESERVER']._serialized_start=201
  _globals['_NAMESERVER']._serialized_end=295
# @@protoc_insertion_point(module_scope)
